### ISSUE TITLE
Use tags.synced to decide whether content is pushed

### ISSUE THREAD

**Issue by Eknir** [ethersphere/beekeeper#158]
It was discovered recently that the simulations don't use the correct logic to decide when a chunk is pushed. Right now, simulations consider a chunk pushed whenever we get back the hash, but a chunk is only pushed whenever we get back a receipt (in the meantime, the chunk is in the pusher queue). 

I suggest to update the logic:

1) Create a tag manually
2) Push the chunk
3) Watch the tags endpoint and consider a chunk synced whenever tags say it is synced

Please note that for content that the tags may not work 100% due to internal logic errors (tags always has been a bit of an issue). Furthermore, it may be the case that, while no receipt is returned, the content is available in the network. For these reasons, it would be optimal that the node tries to retrieve the content even if the tags is not at 100% after a certain timeout and log this success rate separately from the success rate of content that have tags at 100%.

Further reading on tags: https://docs.ethswarm.org/docs/access-the-swarm/syncing/

**Comment by svetomir** [comment]
https://github.com/ethersphere/beekeeper/pull/180
