### ISSUE TITLE
upload worker should take in a max storage radius option

### ISSUE THREAD

**Issue by istae** [ethersphere/beekeeper#400]
the upload worker should take in a max storage radius option so that the uploads can stop once the radius is reached.

acquire the storage radius either from the /reservestate or /status

the idea is after picking an uploader node, the storage radius should be checked (of the uploader). if the radius is above the allowed maximum value, the upload should not happen.
the worker can then sleep for 5-10 min, then repeat the same thing. 

this task applies to the smoke/load job in beekeeper and not the smoke job

the maximum allowed radius will be a new config option passed to the job

**Comment by gacevicljubisa** [comment]
Released with v0.17.0 (https://github.com/ethersphere/beekeeper/releases/tag/v0.17.0)
