### ISSUE TITLE
Adapt Beekeeper for in-cluster deployment via Kubernetes services

### ISSUE THREAD

**Issue by gacevicljubisa** [ethersphere/beekeeper#418]
Ensure that Beekeeper can work through Kubernetes services when the relevant flag is set, allowing internal communication within the cluster, not just through ingress. This includes:
- Modification of the Beekeeper k8s package.
- Updating Beekeeper's configuration to support communication via Kubernetes services.
- Testing and validating the new setup within the Kubernetes cluster.

**Acceptance Criteria:**
- Beekeeper successfully communicates with other components via Kubernetes services when the flag is set.

Requested by: @darkobas2

**Comment by darkobas2** [comment]
Low priority, i have made a dns work around
